name: Ventoy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
     types:
       - published
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Build Ventoy
      run: docker-compose up
    - name: Upload Windows Build
      uses: actions/upload-artifact@v2
      with:
        name: ventoy-windows
        path: INSTALL/ventoy-*windows*
    - name: Upload Linux Build
      uses: actions/upload-artifact@v2
      with:
        name: ventoy-linux
        path: INSTALL/ventoy-*linux*
    - name: Upload LiveCD
      uses: actions/upload-artifact@v2
      with:
        name: ventoy-livecd
        path: INSTALL/ventoy-*livecd*
    - name: Upload SHA256 CheckSum
      uses: actions/upload-artifact@v2
      with:
        name: SHA256SUM
        path: INSTALL/sha256.txt
    - name: Upload Build Log
      uses: actions/upload-artifact@v2
      with:
        name: xxx-build-log
        path: DOC/build.log
